### ISSUE TITLE
Can't boot using two Monitors

### ISSUE THREAD

**Issue by janxnoordwijk** [LemoFire/OpenCore-HP-800G1-USDT-HD4600#1]
Hey, thank you for your effort making this config. Unfortunately i can't boot using both DisplayPorts at once, can't even connect after the system booted using only one port. It's getting stuck at IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0. It boots perfectly using just one monitor. 

I'm using the HP EliteDesk 800 G1 SFF, i wanted to put a GT 730 low profile in it and i had this GPU working in a HP Compaq 6300 Elite, running Catalina. I tried to install Catalina/Big Sur without dGPU and using just one monitor with DisplayPort and it worked flawlessly. But every config i'm trying (your one was the best so far), i'm not getting it to work after connecting a second monitor via DisplayPort. My CPU is i5-4590. I also have a EliteDesk 800 G1 USDT, running Catalina and using a config for TW, SFF and USDT from insanelymac.com where both DisplayPorts are working, but even with that config i can't get it to work on my SFF. Is there anything i might be missing? I'm using BIOS defaults and settings from your readme, updated my BIOS and tried different SMBIOSes. 

The final setup should be capable running four monitors, two of them running through DisplayPort on iGPU and two running trough HDMI and DVI on dGPU. Had this also working on a Optiplex 9010 with a 4x HDMI GT 710, but switched to EliteDesk again and now i'm stuck. 

I know this isn't a tech support thread, but you've got me very far until now and any help would be greatly appreciated. 

![IMG_2846](https://user-images.githubusercontent.com/65429411/121791396-bd60fa80-cbe9-11eb-9f5e-7a542cc70030.jpg)

**Comment by LemoFire** [comment]
Hi, I'm sorry for the untimely reply.  Unfortunately I don't have NVIDIA GPU to help you recreate this situation. Dual monitor can works perfectly on igpu.

You can try to add `shikigva=40` to boot args and swaps boardID to iMac14,2 for better Nvidia Support and whitelists patches.

See [https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/nvidia-gpu.html#kepler-series-gtx-6xx-7xx](https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/nvidia-gpu.html#kepler-series-gtx-6xx-7xx)
