### ISSUE TITLE
I come from China, your efi is perfect

### ISSUE THREAD

**Issue by yvoonekit** [LemoFire/OpenCore-HP-800G1-USDT-HD4600#2]
I come from China, your efi is perfect

**Comment by LemoFire** [comment]
老哥自己人

**Comment by yvoonekit** [comment]
> 老哥自己人

靠，哈哈，我把你的地址发远景里了http://bbs.pcbeta.com/viewthread-1891646-1-1.html

**Comment by LemoFire** [comment]
哈哈哈 nice

**Comment by yvoonekit** [comment]
> 哈哈哈 nice
PlatformInfo>Generic>ROM 里写什么？

**Comment by LemoFire** [comment]
有线网卡MAC地址

**Comment by LemoFire** [comment]
不写可能苹果一些服务用不了

**Comment by yvoonekit** [comment]
> 不写可能苹果一些服务用不了

收到
