### ISSUE TITLE
test

### ISSUE THREAD

**Issue by yvonekit** [LemoFire/OpenCore-HP-800G1-USDT-HD4600#3]
# 史上最完美800G1-USDT oc efi

## OpenCore-HP-800G1-USDT-HD4600

OpenCore for HP 800G1 USDT with HD4600 and Intel WLAN

## OC information

- OC Version: 0.7.0
- Tested OS Version: 11.4 (20F71)

## Working

- WIFI
- Sound
- USB Port(fixed on 0.7.0)

## Not working

- 4K (No equipment for testing, if you have one, you can submit PR)

## Before installation

**star this project ( > ω < )**

***Don't try to use the VGA port to boot!***

#### Edit config.plist

**At first, please complete the 'PlatformInfo' by yourself.** https://dortania.github.io/OpenCore-Install-Guide/config.plist/haswell.html#platforminfo

- PlatformInfo>Generic>MLB
- PlatformInfo>Generic>ROM
- PlatformInfo>Generic>SystemSerialNumber
- PlatformInfo>Generic>SystemUUID

#### Disable

- Fast Boot -> Disabled
- Secure Boot -> Disabled
- Security -> VTd -> Disabled

#### Set

- Storage -> Storage Options -> SATA Emulation > AHCI

## Kext information

| Name          | Version |
| ------------- | :-----: |
| Lilu          |  1.5.3  |
| VirtualSMC    |  1.2.4  |
| WhateverGreen |  1.5.0  |
| AppleALC      |  1.6.1  |
| AirportItlwm  |  2.0.0  |
| IntelMausi    |  1.0.6  |
| USBInjectAll  |  0.7.6  |

下载地址：

https://github.com/LemoFire/OpenCore-HP-800G1-USDT-HD4600/archive/refs/tags/OC0.7.0-1.zip
![Imgur](https://i.imgur.com/GLOXO52.png)

**Comment by LemoFire** [comment]
なに！？
