### ISSUE TITLE
我已经更新了7.2版本EFI

### ISSUE THREAD

**Issue by yxmingh** [LemoFire/OpenCore-HP-800G1-USDT-HD4600#4]
系统版本：11.5.1
简单配置：4690+16G（1600）+256G+BCM94360CS2
状态：基本所有功能可用，我删除了博通网卡的驱动，因为用的白果卡，睡眠、隔空投送、隔空接力、USB全部可用
一些问题：不知道你在12版本里面用的咋样，我从11.5.1升级以后，升级之前EFI分区里的文件就进不了系统了，不过我有备份EFI可以使用，今天更新了7.2，偶尔还是进不了系统很随机，还有个小问题是这个EFI好像用不了双屏幕

**Comment by UzkiS** [comment]
双屏有的时候可以有的时候不行（可能有运气成分因为我几次都是可以双屏直接开机的，我现在usdt暂时坏了换了dm这个只是根据现在dm的efi更改的没有测试过的版本，等到时候usdt修好我会再调试一下显卡）  我没有很看得明白你的问题，进不了系统的话看看开机跑码卡在哪里，截个图发过来看看

**Comment by UzkiS** [comment]
虽然没有测试 但是如果是11系统的efi应该不会有特别大的问题（蜜汁自信 > v <

12系统也就换了intel的airport驱动 没有什么特别需要更改的地方

**Comment by yxmingh** [comment]
双屏无所谓，我就是之前试了一下，不过卡码的问题很诡异
![image](https://user-images.githubusercontent.com/70571264/127984556-51701c6c-46c7-4d7b-a11f-b54d33ae814e.png)

**Comment by UzkiS** [comment]
确实很诡异 我直接看不懂

**Comment by UzkiS** [comment]
不影响就直接重启 我没遇过你这个问题

**Comment by yxmingh** [comment]
如果出现这个就进不去系统了，偶尔会出现不是每次都有，我查过这个问题，原因是某些驱动不受支持，但一般就是网卡驱动版本或者USB驱动版本不对导致的，我一般开机以后基本不关机最长时候2月，不换EFI的话就不会重启，不行我就试试更新到12看看，反正我有2块盘，一块停留在11.5.0(怕出问题所以其中一块没升级)一块升级12

**Comment by UzkiS** [comment]
嗯 可以排除下网卡原因（因为驱动我这边就网卡和你不同） 基本无痛升级 如果点升级不了（有升级操作但是开机版本没变化），就把SecureBootModel改成Disabled就行了

**Comment by yxmingh** [comment]
我再自己试试吧，非常感谢。
