### ISSUE TITLE
大佬我想请教下关于alcid的问题

### ISSUE THREAD

**Issue by akudamatata** [LemoFire/OpenCore-HP-800G1-USDT-HD4600#9]
我也是这款机器 咱们配置差不多 升级到11.6.1之后声卡没了 
我在官网看参数是ALC221 布局id为11 15 88 我都试过了alcid= 并没有反应
参考你的device properites填写也不行 
我是oc6.4 请求指点迷津

**Comment by akudamatata** [comment]
[EFI.zip](https://github.com/LemoFire/OpenCore-HP-800G1-USDT-HD4600/files/7477412/EFI.zip)
这是我的efi

**Comment by UzkiS** [comment]
先更新一下OC 然后尝试修复iqr
